jobs:
# CI for BOX
  - name: box-ci
    type: runCI
    steps:
      - GET: box-repo
      - PUT: box-img

# manifest gen for BOX
  - name: box-man
    type: manifest
    steps:
      - GET: box-img
      - GET: box-img-opts

# CI for dv
  - name: dv-ci
    type: runCI
    steps:
      - GET: dv-repo
      - PUT: dv-img

# manifest gen for dv
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-img
      - GET: dv-img-opts
      - GET: s1
      
  - name: box-test-triton
    type: manifest
    steps:
      - GET: box-t-params
      - GET: box-man
      
  - name: dv-test
    type: manifest
    steps:
      - GET: dv-man
      - GET: dv-params
      - GET: env-test-triton
